server:
  port: '8081'
spring:
  kafka:
    consumer:
      bootstrap-servers: '172.27.223.17:9092, 172.27.223.17:9093, 172.27.223.17:9094'
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    producer:
      bootstrap-servers: '172.27.223.17:9092, 172.27.223.17:9093, 172.27.223.17:9094'
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: library-events
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
